#!/usr/bin/env bash

NAME=${NAME}
SOURCE_FILE=new_raspilot/modules/`echo ${NAME} | perl -ne 'print lc(join("_", split(/(?=[A-Z])/)))'`.py


if [[ -a ${SOURCE_FILE} ]]; then
  echo ${SOURCE_FILE} "already exists."
  exit;
fi

cat << EOF > ${SOURCE_FILE}
from new_raspilot.core.base_started_module import BaseStartedModule


class ${NAME}(BaseStartedModule):
    def __init__(self):
        super().__init__()

    def _execute_start(self):
        return True

    def _execute_stop(self):
        pass

    def load(self):
        return True

EOF
