#!/usr/bin/env bash

set -e

if !grep -Fq "export RASPILOT_PATH=" ~/.bashrc; then
    echo "export RASPILOT_PATH=$(pwd)" >> ~/.bashrc
fi
echo "RASPILOT_PATH is set to ${RASPILOT_PATH}"

sudo cp ${RASPILOT_PATH}/scripts/run /usr/bin/raspilot-run
sudo cp ${RASPILOT_PATH}/scripts/update /usr/bin/raspilot-update
sudo cp ${RASPILOT_PATH}/scripts/uninstall /usr/bin/raspilot-uninstall
echo "Scripts raspilot-start, raspilot-update, raspilot-uninstall installed to /usr/bin"